### PR TITLE
Npm scripts in root, workflow update, and latest dependencies

### LINKED ISSUE #13: [Enhancement Request] Cashing npm dependencies in webpack workflow
### Describe the Enhancement

The webpack workflow is installing npm dependencies each time it runs. We can speed this process up by cashing the dependencies. This way we can store all of our dependencies and stop installing them on 3 separate version of node. We may also want to think about using 1 or 2 versions of node instead of 3. Maybe just 14 and the latest.

### Describe the current behavior

The current webpack workflow installs our npm dependencies every time it runs.

### Describe alternatives to your enhancement

_No response_

### Screenshots

_No response_

### Additional Context

_No response_

### LINKED ISSUE #22: [Enhancement Request] npm scripts from root
### Describe the Enhancement

Allowing npm scripts to run from root directory.

### Describe the current behavior

You have to change directory into react-blahblahblah. No body wants to do all that when building and running.

### Describe alternatives to your enhancement

_No response_

### Screenshots

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by anthonyfabius**
# Pull Request

## Description

I made it so you can build webpack from the root directory. I also made it so the workflow only runs on node 14 and the latest version of node. I also tried adding cache stuff but I don't really know if it works yet. Updated to latest dependencies also.

Fixes #22 & Fixed #13 

## Type of change

- [ ] Bug fix (change which fixes an issue)
- [x] Enhancement (change which alters existing functionality)
- [ ] New feature (change which adds new functionality)
- [ ] This change requires a wiki/documentation update

## How Has This Been Tested?

I can't. Forgot it had to be merged into main.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

Try to checkoff as much as possible if not everything!

### CODE REVIEW

**Comment by anthonyfabius** [comment]
@LeadFreeCandy maybe im stupid but can you check out the previous 2 commits. For some reason the build for the latest version of npm was failing but when I added node 18 it starts passing the tests. I don't understand why but maybe another set of eyes will understand.

**Comment by LeadFreeCandy** [comment]
If you don't squash these commits so help me god

**Comment by LeadFreeCandy** [comment]
I'll take a look later today

**Comment by anthonyfabius** [comment]
> If you don't squash these commits so help me god

I am actively fighting with this yml file. We can squash on merge tbh because there are bound to be 15 more commits 💀

**Comment by anthonyfabius** [comment]
this pr is doomed lmao. Imma just close and start from scratch tbh

**Pull request closed without merging**
